# Generated by Django 4.1.7 on 2023-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
    ]
