# Generated by Django 4.1.7 on 2023-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newuser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
