# Generated by Django 4.1.7 on 2023-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_type', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('property_location', models.TextField(blank=True, max_length=100, null=True)),
                ('rent_money', models.IntegerField(blank=True, null=True)),
                ('money_type', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_face', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_size', models.IntegerField(blank=True, null=True)),
                ('numerical_value_type', models.TextField(blank=True, max_length=50, null=True)),
                ('area_description', models.TextField(blank=True, max_length=250, null=True)),
                ('rent_photo', models.ImageField(blank=True, null=True, upload_to='rent')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
