# Generated by Django 4.1.7 on 2023-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrent',
            name='money_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownerrent',
            name='plot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownerrent',
            name='rent_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
