# Generated by Django 4.1.7 on 2023-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_ownerrent_money_type_alter_ownerrent_plot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrent',
            name='money_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
