# Generated by Django 4.1.7 on 2023-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_ownerrent_money_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrent',
            name='user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
