# Generated by Django 4.1.7 on 2023-03-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_sell_land'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_land',
            old_name='division',
            new_name='divission',
        ),
    ]
