# Generated by Django 4.1.7 on 2023-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_ownerrent_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrent',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
